version: '3.8'

services:
  app:
    build: .
    container_name: jira-decomposition-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    container_name: jira-decomposition-db
    environment:
      POSTGRES_DB: jira_decomposition
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: jira-decomposition-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - dev

volumes:
  postgres_data:
  
networks:
  app-network:
    driver: bridge