services:
  app:
    build: .
    container_name: jira-decomposition-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
    restart: unless-stopped